[build]
  command = "npm run build"
  publish = ".next"
  ignore = "false"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_IGNORE_ESLINT = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# The following redirects are not needed with the Next.js plugin and can be removed
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200 