[build]
  command = "npm run build || true"
  publish = ".next"
  ignore = "false"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_IGNORE_ESLINT = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 